--
-- PostgreSQL database dump
--

\restrict lJ4yKtf9csZce5A2fzX3fAslX9s5cf5lU5yA1uj9IC1qHElrZFNaGiW2X7S8PCI

-- Dumped from database version 15.19 (Debian 15.19-0+deb12u1)
-- Dumped by pg_dump version 15.19 (Debian 15.19-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: corebanking
--

CREATE TABLE public.account (
    id integer NOT NULL,
    account_number character varying(30) NOT NULL,
    customer_id integer NOT NULL,
    type character varying(20) NOT NULL,
    balance bigint DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT chk_account_balance CHECK ((balance >= 0)),
    CONSTRAINT chk_account_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'BLOCKED'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT chk_account_type CHECK (((type)::text = ANY ((ARRAY['CURRENT'::character varying, 'SAVINGS'::character varying])::text[])))
);


ALTER TABLE public.account OWNER TO corebanking;

--
-- Name: branch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.branch (
    id bigint NOT NULL,
    branch_code character(7) NOT NULL,
    name character varying(150) NOT NULL,
    city_id bigint NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_branch_code CHECK ((branch_code ~ '^[0-9]{7}$'::text)),
    CONSTRAINT ck_branch_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'CLOSED'::character varying])::text[])))
);


ALTER TABLE public.branch OWNER TO postgres;

--
-- Name: branch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.branch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: city; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.city (
    id bigint NOT NULL,
    province_id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.city OWNER TO postgres;

--
-- Name: city_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.city ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id bigint NOT NULL,
    code character(3) NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT ck_country_code CHECK ((code ~ '^[0-9]{3}$'::text))
);


ALTER TABLE public.country OWNER TO postgres;

--
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id bigint NOT NULL,
    code character(3) NOT NULL,
    numeric_code character(3) NOT NULL,
    name character varying(100) NOT NULL,
    minor_unit smallint NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_currency_code CHECK ((code ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT ck_currency_minor_unit CHECK (((minor_unit >= 0) AND (minor_unit <= 6))),
    CONSTRAINT ck_currency_numeric_code CHECK ((numeric_code ~ '^[0-9]{3}$'::text)),
    CONSTRAINT ck_currency_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.customer_id_seq
    START WITH 1003
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.customer_id_seq OWNER TO postgres;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: corebanking
--

CREATE TABLE public.customer (
    id bigint DEFAULT nextval('public.customer_id_seq'::regclass) NOT NULL,
    national_id character varying(20) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL
);


ALTER TABLE public.customer OWNER TO corebanking;

--
-- Name: province; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.province (
    id bigint NOT NULL,
    country_id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.province OWNER TO postgres;

--
-- Name: province_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.province ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.province_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: corebanking
--

CREATE SEQUENCE public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_id_seq OWNER TO corebanking;

--
-- Name: transaction; Type: TABLE; Schema: public; Owner: corebanking
--

CREATE TABLE public.transaction (
    id bigint DEFAULT nextval('public.transaction_id_seq'::regclass) NOT NULL,
    account_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    amount bigint NOT NULL,
    description character varying(255),
    CONSTRAINT chk_transaction_amount CHECK ((amount > 0)),
    CONSTRAINT chk_transaction_type CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying])::text[])))
);


ALTER TABLE public.transaction OWNER TO corebanking;

--
-- Name: transfer; Type: TABLE; Schema: public; Owner: corebanking
--

CREATE TABLE public.transfer (
    id bigint NOT NULL,
    source_account_id bigint NOT NULL,
    destination_account_id bigint NOT NULL,
    amount bigint NOT NULL,
    description character varying(255),
    status character varying(20) NOT NULL,
    CONSTRAINT chk_transfer_amount CHECK ((amount > 0)),
    CONSTRAINT chk_transfer_different_accounts CHECK ((source_account_id <> destination_account_id)),
    CONSTRAINT chk_transfer_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.transfer OWNER TO corebanking;

--
-- Name: transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: corebanking
--

CREATE SEQUENCE public.transfer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transfer_id_seq OWNER TO corebanking;

--
-- Name: transfer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: corebanking
--

ALTER SEQUENCE public.transfer_id_seq OWNED BY public.transfer.id;


--
-- Name: transfer id; Type: DEFAULT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.transfer ALTER COLUMN id SET DEFAULT nextval('public.transfer_id_seq'::regclass);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: corebanking
--

COPY public.account (id, account_number, customer_id, type, balance, status) FROM stdin;
5002	0100123456790	1001	CURRENT	70000000	ACTIVE
5001	0100123456789	1001	CURRENT	25000000	ACTIVE
\.


--
-- Data for Name: branch; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.branch (id, branch_code, name, city_id, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: city; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.city (id, province_id, code, name) FROM stdin;
\.


--
-- Data for Name: country; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.country (id, code, name) FROM stdin;
\.


--
-- Data for Name: currency; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.currency (id, code, numeric_code, name, minor_unit, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: corebanking
--

COPY public.customer (id, national_id, first_name, last_name, status) FROM stdin;
1002	1234567891	Reza	Ahmadi Updated	INACTIVE
1001	1234567890	Ahmad	Babayi	BLOCKED
1003	0012345678	Ali	Ahmadi	ACTIVE
1004	0012345679	Reza	Ahmadi	ACTIVE
1005	0012345680	Reza	Ahmadi	ACTIVE
1009	0012345682	Ali	Ahmadi	ACTIVE
1010	0012345683	Reza	Ahmadi	ACTIVE
1011	0012345684	Hasan	Ahmadi	ACTIVE
1012	0012345699	Test	AutoId	ACTIVE
1013	0012345700	Ali	Test	ACTIVE
1014	1462936113	احمد	پوربابائی	ACTIVE
\.


--
-- Data for Name: province; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.province (id, country_id, code, name) FROM stdin;
\.


--
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: corebanking
--

COPY public.transaction (id, account_id, type, amount, description) FROM stdin;
2	5001	DEPOSIT	5000000	Real atomic deposit test
4	5001	WITHDRAWAL	5000000	Real atomic withdrawal test
6	5001	WITHDRAWAL	10000000	First real transfer test
7	5002	DEPOSIT	10000000	First real transfer test
8	5001	WITHDRAWAL	10000000	First real transfer test
9	5002	DEPOSIT	10000000	First real transfer test
12	5001	WITHDRAWAL	5000000	AccountService SELECT FOR UPDATE test
45	5001	WITHDRAWAL	5000000	AccountService SELECT FOR UPDATE test
46	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
47	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
48	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
49	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
50	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
51	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
52	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
53	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
54	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
55	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
56	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
57	5001	WITHDRAWAL	5000000	Connection aware withdrawal test
\.


--
-- Data for Name: transfer; Type: TABLE DATA; Schema: public; Owner: corebanking
--

COPY public.transfer (id, source_account_id, destination_account_id, amount, description, status) FROM stdin;
1	5001	5002	10000000	First real transfer test	COMPLETED
2	5001	5002	10000000	First real transfer test	COMPLETED
\.


--
-- Name: branch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.branch_id_seq', 1, false);


--
-- Name: city_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.city_id_seq', 1, false);


--
-- Name: country_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.country_id_seq', 1, false);


--
-- Name: currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_id_seq', 1, false);


--
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 1014, true);


--
-- Name: province_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.province_id_seq', 1, false);


--
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: corebanking
--

SELECT pg_catalog.setval('public.transaction_id_seq', 57, true);


--
-- Name: transfer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: corebanking
--

SELECT pg_catalog.setval('public.transfer_id_seq', 3, true);


--
-- Name: account account_account_number_key; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_account_number_key UNIQUE (account_number);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: branch branch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT branch_pkey PRIMARY KEY (id);


--
-- Name: city city_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.city
    ADD CONSTRAINT city_pkey PRIMARY KEY (id);


--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id);


--
-- Name: customer customer_national_id_key; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_national_id_key UNIQUE (national_id);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- Name: province province_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.province
    ADD CONSTRAINT province_pkey PRIMARY KEY (id);


--
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


--
-- Name: transfer transfer_pkey; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.transfer
    ADD CONSTRAINT transfer_pkey PRIMARY KEY (id);


--
-- Name: branch uq_branch_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT uq_branch_code UNIQUE (branch_code);


--
-- Name: city uq_city_province_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.city
    ADD CONSTRAINT uq_city_province_code UNIQUE (province_id, code);


--
-- Name: country uq_country_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT uq_country_code UNIQUE (code);


--
-- Name: country uq_country_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT uq_country_name UNIQUE (name);


--
-- Name: currency uq_currency_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT uq_currency_code UNIQUE (code);


--
-- Name: currency uq_currency_numeric_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT uq_currency_numeric_code UNIQUE (numeric_code);


--
-- Name: customer uq_customer_national_id; Type: CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT uq_customer_national_id UNIQUE (national_id);


--
-- Name: province uq_province_country_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.province
    ADD CONSTRAINT uq_province_country_code UNIQUE (country_id, code);


--
-- Name: idx_branch_city_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_branch_city_id ON public.branch USING btree (city_id);


--
-- Name: idx_city_province_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_city_province_id ON public.city USING btree (province_id);


--
-- Name: idx_province_country_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_province_country_id ON public.province USING btree (country_id);


--
-- Name: account fk_account_customer; Type: FK CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- Name: branch fk_branch_city; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT fk_branch_city FOREIGN KEY (city_id) REFERENCES public.city(id);


--
-- Name: city fk_city_province; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.city
    ADD CONSTRAINT fk_city_province FOREIGN KEY (province_id) REFERENCES public.province(id);


--
-- Name: province fk_province_country; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.province
    ADD CONSTRAINT fk_province_country FOREIGN KEY (country_id) REFERENCES public.country(id);


--
-- Name: transaction fk_transaction_account; Type: FK CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- Name: transfer fk_transfer_destination_account; Type: FK CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.transfer
    ADD CONSTRAINT fk_transfer_destination_account FOREIGN KEY (destination_account_id) REFERENCES public.account(id);


--
-- Name: transfer fk_transfer_source_account; Type: FK CONSTRAINT; Schema: public; Owner: corebanking
--

ALTER TABLE ONLY public.transfer
    ADD CONSTRAINT fk_transfer_source_account FOREIGN KEY (source_account_id) REFERENCES public.account(id);


--
-- Name: SEQUENCE customer_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE public.customer_id_seq TO corebanking;


--
-- PostgreSQL database dump complete
--

\unrestrict lJ4yKtf9csZce5A2fzX3fAslX9s5cf5lU5yA1uj9IC1qHElrZFNaGiW2X7S8PCI

