-- ============================================================
-- Core Banking Database
-- Schema 001
-- Geography and Currency
-- PostgreSQL
-- ============================================================

-- ============================================================
-- 1. country
-- ============================================================

CREATE TABLE country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code CHAR(3) NOT NULL,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_country_code UNIQUE (code),
    CONSTRAINT uq_country_name UNIQUE (name),

    CONSTRAINT ck_country_code
        CHECK (code ~ '^[0-9]{3}$')
);


-- ============================================================
-- 2. province
-- ============================================================

CREATE TABLE province (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    country_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT fk_province_country
        FOREIGN KEY (country_id)
        REFERENCES country(id),

    CONSTRAINT uq_province_country_code
        UNIQUE (country_id, code)
);


-- ============================================================
-- 3. city
-- ============================================================

CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    province_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT fk_city_province
        FOREIGN KEY (province_id)
        REFERENCES province(id),

    CONSTRAINT uq_city_province_code
        UNIQUE (province_id, code)
);


-- ============================================================
-- 4. branch
-- ============================================================

CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    branch_code CHAR(7) NOT NULL,
    name VARCHAR(150) NOT NULL,
    city_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_branch_city
        FOREIGN KEY (city_id)
        REFERENCES city(id),

    CONSTRAINT uq_branch_code
        UNIQUE (branch_code),

    CONSTRAINT ck_branch_code
        CHECK (branch_code ~ '^[0-9]{7}$'),

    CONSTRAINT ck_branch_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'CLOSED'))
);


-- ============================================================
-- 5. currency
-- ============================================================

CREATE TABLE currency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code CHAR(3) NOT NULL,
    numeric_code CHAR(3) NOT NULL,
    name VARCHAR(100) NOT NULL,

    minor_unit SMALLINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_currency_code
        UNIQUE (code),

    CONSTRAINT uq_currency_numeric_code
        UNIQUE (numeric_code),

    CONSTRAINT ck_currency_code
        CHECK (code ~ '^[A-Z]{3}$'),

    CONSTRAINT ck_currency_numeric_code
        CHECK (numeric_code ~ '^[0-9]{3}$'),

    CONSTRAINT ck_currency_minor_unit
        CHECK (minor_unit BETWEEN 0 AND 6),

    CONSTRAINT ck_currency_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


-- ============================================================
-- Indexes for foreign keys
-- ============================================================

CREATE INDEX idx_province_country_id
    ON province(country_id);

CREATE INDEX idx_city_province_id
    ON city(province_id);

CREATE INDEX idx_branch_city_id
    ON branch(city_id);
