-- ============================================================
-- Core Banking Database
-- Schema 003
-- Customer Model
-- PostgreSQL
-- ============================================================

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_number CHAR(10) NOT NULL,

    customer_type VARCHAR(20) NOT NULL,

    nationality_code CHAR(3) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_customer_number
        UNIQUE (customer_number),

    CONSTRAINT fk_customer_nationality
        FOREIGN KEY (nationality_code)
        REFERENCES country(code),

    CONSTRAINT ck_customer_number
        CHECK (customer_number ~ '^[0-9]{10}$'),

    CONSTRAINT ck_customer_type
        CHECK (
            customer_type IN (
                'INDIVIDUAL',
                'LEGAL_ENTITY'
            )
        ),

    CONSTRAINT ck_customer_nationality_code
        CHECK (
            nationality_code ~ '^[0-9]{3}$'
        ),

    CONSTRAINT ck_customer_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'BLOCKED',
                'CLOSED'
            )
        )
);


CREATE TABLE individual (
    customer_id BIGINT PRIMARY KEY,

    national_id VARCHAR(20) NOT NULL,

    first_name VARCHAR(100) NOT NULL,

    last_name VARCHAR(100) NOT NULL,

    CONSTRAINT fk_individual_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_individual_national_id
        UNIQUE (national_id),

    CONSTRAINT ck_individual_national_id
        CHECK (national_id <> ''),

    CONSTRAINT ck_individual_first_name
        CHECK (first_name <> ''),

    CONSTRAINT ck_individual_last_name
        CHECK (last_name <> '')
);


CREATE TABLE legal_entity (
    customer_id BIGINT PRIMARY KEY,

    legal_id VARCHAR(30) NOT NULL,

    legal_name VARCHAR(200) NOT NULL,

    registration_number VARCHAR(50),

    CONSTRAINT fk_legal_entity_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_legal_entity_legal_id
        UNIQUE (legal_id),

    CONSTRAINT ck_legal_entity_legal_id
        CHECK (legal_id <> ''),

    CONSTRAINT ck_legal_entity_legal_name
        CHECK (legal_name <> '')
);


CREATE INDEX idx_customer_nationality_code
    ON customer(nationality_code);

CREATE INDEX idx_customer_status
    ON customer(status);
