-- ============================================================
-- Core Banking Database
-- Schema 005
-- Account Type, Product, Ledger Account and Account
-- PostgreSQL
-- ============================================================


-- ============================================================
-- 1. ACCOUNT TYPE
-- ============================================================

CREATE TABLE account_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code CHAR(2) NOT NULL,

    name VARCHAR(100) NOT NULL,

    currency_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_account_type_code
        UNIQUE (code),

    /*
     * This composite uniqueness is used by PRODUCT and ACCOUNT
     * foreign keys to guarantee currency consistency.
     */
    CONSTRAINT uq_account_type_id_currency
        UNIQUE (id, currency_id),

    CONSTRAINT fk_account_type_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT ck_account_type_code
        CHECK (code ~ '^[0-9]{2}$'),

    CONSTRAINT ck_account_type_name
        CHECK (name <> ''),

    CONSTRAINT ck_account_type_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 2. PRODUCT
-- ============================================================

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(50) NOT NULL,

    name VARCHAR(150) NOT NULL,

    account_type_id BIGINT NOT NULL,

    currency_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    effective_from DATE NOT NULL,

    effective_to DATE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_product_code
        UNIQUE (code),

    /*
     * Used as the target of the composite foreign key
     * from ACCOUNT.
     */
    CONSTRAINT uq_product_id_type_currency
        UNIQUE (
            id,
            account_type_id,
            currency_id
        ),

    /*
     * Guarantees that the Product currency is exactly
     * the same currency defined by its Account Type.
     */
    CONSTRAINT fk_product_account_type_currency
        FOREIGN KEY (
            account_type_id,
            currency_id
        )
        REFERENCES account_type (
            id,
            currency_id
        ),

    CONSTRAINT fk_product_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT ck_product_code
        CHECK (code <> ''),

    CONSTRAINT ck_product_name
        CHECK (name <> ''),

    CONSTRAINT ck_product_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        ),

    CONSTRAINT ck_product_effective_dates
        CHECK (
            effective_to IS NULL
            OR effective_to >= effective_from
        )
);


-- ============================================================
-- 3. LEDGER ACCOUNT
-- ============================================================

CREATE TABLE ledger_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code CHAR(8) NOT NULL,

    name VARCHAR(200) NOT NULL,

    account_category VARCHAR(20) NOT NULL,

    parent_id BIGINT,

    currency_id BIGINT NOT NULL,

    is_postable BOOLEAN NOT NULL DEFAULT TRUE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ledger_account_code
        UNIQUE (code),

    CONSTRAINT fk_ledger_account_parent
        FOREIGN KEY (parent_id)
        REFERENCES ledger_account(id),

    CONSTRAINT fk_ledger_account_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT ck_ledger_account_code
        CHECK (code ~ '^[0-9]{8}$'),

    CONSTRAINT ck_ledger_account_name
        CHECK (name <> ''),

    CONSTRAINT ck_ledger_account_category
        CHECK (
            account_category IN (
                'ASSET',
                'LIABILITY',
                'EQUITY',
                'REVENUE',
                'EXPENSE'
            )
        ),

    CONSTRAINT ck_ledger_account_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        ),

    /*
     * A ledger account cannot be its own parent.
     */
    CONSTRAINT ck_ledger_account_not_self_parent
        CHECK (
            parent_id IS NULL
            OR parent_id <> id
        )
);


-- ============================================================
-- 4. ACCOUNT
-- ============================================================

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_number CHAR(13) NOT NULL,

    account_type_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,

    currency_id BIGINT NOT NULL,

    opening_branch_id BIGINT NOT NULL,

    ledger_account_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    closed_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_account_number
        UNIQUE (account_number),

    /*
     * Guarantees that the Account references a Product
     * whose Account Type and Currency are exactly the
     * same values stored in this Account.
     */
    CONSTRAINT fk_account_product_type_currency
        FOREIGN KEY (
            product_id,
            account_type_id,
            currency_id
        )
        REFERENCES product (
            id,
            account_type_id,
            currency_id
        ),

    /*
     * Direct FK to Account Type.
     * This also documents the relationship explicitly.
     */
    CONSTRAINT fk_account_account_type
        FOREIGN KEY (account_type_id)
        REFERENCES account_type(id),

    /*
     * Direct FK to Currency.
     */
    CONSTRAINT fk_account_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT fk_account_opening_branch
        FOREIGN KEY (opening_branch_id)
        REFERENCES branch(id),

    CONSTRAINT fk_account_ledger_account
        FOREIGN KEY (ledger_account_id)
        REFERENCES ledger_account(id),

    CONSTRAINT ck_account_number
        CHECK (
            account_number ~ '^[0-9]{13}$'
        ),

    CONSTRAINT ck_account_status
        CHECK (
            status IN (
                'ACTIVE',
                'DORMANT',
                'BLOCKED',
                'CLOSED'
            )
        ),

    CONSTRAINT ck_account_closed_at
        CHECK (
            closed_at IS NULL
            OR closed_at >= opened_at
        )
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_account_type_currency_id
    ON account_type(currency_id);


CREATE INDEX idx_product_account_type_id
    ON product(account_type_id);


CREATE INDEX idx_product_currency_id
    ON product(currency_id);


CREATE INDEX idx_ledger_account_parent_id
    ON ledger_account(parent_id);


CREATE INDEX idx_ledger_account_currency_id
    ON ledger_account(currency_id);


CREATE INDEX idx_account_account_type_id
    ON account(account_type_id);


CREATE INDEX idx_account_product_id
    ON account(product_id);


CREATE INDEX idx_account_currency_id
    ON account(currency_id);


CREATE INDEX idx_account_opening_branch_id
    ON account(opening_branch_id);


CREATE INDEX idx_account_ledger_account_id
    ON account(ledger_account_id);


CREATE INDEX idx_account_status
    ON account(status);
