-- ============================================================
-- Core Banking Database
-- Schema 006
-- Account Relationships and Signing Mandates
-- PostgreSQL
-- ============================================================


-- ============================================================
-- 1. ACCOUNT OWNER
-- ============================================================

CREATE TABLE account_owner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_id BIGINT NOT NULL,

    customer_id BIGINT NOT NULL,

    valid_from DATE NOT NULL,

    valid_to DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_owner_account
        FOREIGN KEY (account_id)
        REFERENCES account(id),

    CONSTRAINT fk_account_owner_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id),

    CONSTRAINT ck_account_owner_dates
        CHECK (
            valid_to IS NULL
            OR valid_to >= valid_from
        ),

    CONSTRAINT ck_account_owner_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 2. ACCOUNT AUTHORIZATION
-- ============================================================

CREATE TABLE account_authorization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_id BIGINT NOT NULL,

    customer_id BIGINT NOT NULL,

    authorization_type VARCHAR(30) NOT NULL,

    valid_from DATE NOT NULL,

    valid_to DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_authorization_account
        FOREIGN KEY (account_id)
        REFERENCES account(id),

    CONSTRAINT fk_account_authorization_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id),

    CONSTRAINT ck_account_authorization_type
        CHECK (
            authorization_type IN (
                'POWER_OF_ATTORNEY',
                'LEGAL_GUARDIAN',
                'LEGAL_REPRESENTATIVE',
                'AUTHORIZED_SIGNATORY'
            )
        ),

    CONSTRAINT ck_account_authorization_dates
        CHECK (
            valid_to IS NULL
            OR valid_to >= valid_from
        ),

    CONSTRAINT ck_account_authorization_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 3. LEGAL ENTITY BOARD MEMBER
-- ============================================================

CREATE TABLE legal_entity_board_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    legal_entity_customer_id BIGINT NOT NULL,

    customer_id BIGINT NOT NULL,

    position VARCHAR(100) NOT NULL,

    start_date DATE NOT NULL,

    end_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_board_member_legal_entity
        FOREIGN KEY (legal_entity_customer_id)
        REFERENCES customer(id),

    CONSTRAINT fk_board_member_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id),

    CONSTRAINT ck_board_member_not_same_customer
        CHECK (
            legal_entity_customer_id <> customer_id
        ),

    CONSTRAINT ck_board_member_position
        CHECK (
            position <> ''
        ),

    CONSTRAINT ck_board_member_dates
        CHECK (
            end_date IS NULL
            OR end_date >= start_date
        ),

    CONSTRAINT ck_board_member_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 4. LEGAL ENTITY SHAREHOLDER
-- ============================================================

CREATE TABLE legal_entity_shareholder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    legal_entity_customer_id BIGINT NOT NULL,

    shareholder_customer_id BIGINT NOT NULL,

    ownership_percentage NUMERIC(9,6),

    share_count NUMERIC(20,6),

    start_date DATE NOT NULL,

    end_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_shareholder_legal_entity
        FOREIGN KEY (legal_entity_customer_id)
        REFERENCES customer(id),

    CONSTRAINT fk_shareholder_customer
        FOREIGN KEY (shareholder_customer_id)
        REFERENCES customer(id),

    CONSTRAINT ck_shareholder_not_same_customer
        CHECK (
            legal_entity_customer_id <> shareholder_customer_id
        ),

    CONSTRAINT ck_shareholder_ownership_percentage
        CHECK (
            ownership_percentage IS NULL
            OR (
                ownership_percentage > 0
                AND ownership_percentage <= 100
            )
        ),

    CONSTRAINT ck_shareholder_share_count
        CHECK (
            share_count IS NULL
            OR share_count > 0
        ),

    CONSTRAINT ck_shareholder_dates
        CHECK (
            end_date IS NULL
            OR end_date >= start_date
        ),

    CONSTRAINT ck_shareholder_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 5. ACCOUNT MANDATE
-- ============================================================

CREATE TABLE account_mandate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_id BIGINT NOT NULL,

    name VARCHAR(150) NOT NULL,

    valid_from DATE NOT NULL,

    valid_to DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_mandate_account
        FOREIGN KEY (account_id)
        REFERENCES account(id),

    CONSTRAINT ck_account_mandate_name
        CHECK (
            name <> ''
        ),

    CONSTRAINT ck_account_mandate_dates
        CHECK (
            valid_to IS NULL
            OR valid_to >= valid_from
        ),

    CONSTRAINT ck_account_mandate_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 6. ACCOUNT MANDATE PARTY
-- ============================================================

CREATE TABLE account_mandate_party (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mandate_id BIGINT NOT NULL,

    customer_id BIGINT NOT NULL,

    role VARCHAR(30) NOT NULL DEFAULT 'SIGNATORY',

    valid_from DATE NOT NULL,

    valid_to DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_mandate_party_mandate
        FOREIGN KEY (mandate_id)
        REFERENCES account_mandate(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_account_mandate_party_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id),

    CONSTRAINT ck_account_mandate_party_role
        CHECK (
            role IN (
                'SIGNATORY'
            )
        ),

    CONSTRAINT ck_account_mandate_party_dates
        CHECK (
            valid_to IS NULL
            OR valid_to >= valid_from
        ),

    CONSTRAINT ck_account_mandate_party_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- 7. ACCOUNT MANDATE RULE
-- ============================================================

CREATE TABLE account_mandate_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mandate_id BIGINT NOT NULL,

    operation_type VARCHAR(30) NOT NULL,

    required_signatures SMALLINT NOT NULL,

    valid_from DATE NOT NULL,

    valid_to DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_mandate_rule_mandate
        FOREIGN KEY (mandate_id)
        REFERENCES account_mandate(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_account_mandate_rule_operation
        CHECK (
            operation_type IN (
                'WITHDRAWAL',
                'TRANSFER',
                'PAYMENT',
                'CLOSE_ACCOUNT'
            )
        ),

    CONSTRAINT ck_account_mandate_rule_required_signatures
        CHECK (
            required_signatures >= 1
        ),

    CONSTRAINT ck_account_mandate_rule_dates
        CHECK (
            valid_to IS NULL
            OR valid_to >= valid_from
        ),

    CONSTRAINT ck_account_mandate_rule_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_account_owner_customer_id
    ON account_owner(customer_id);

CREATE UNIQUE INDEX uq_account_owner_active
    ON account_owner(account_id, customer_id)
    WHERE status = 'ACTIVE';


CREATE INDEX idx_account_authorization_customer_id
    ON account_authorization(customer_id);

CREATE UNIQUE INDEX uq_account_authorization_active
    ON account_authorization(
        account_id,
        customer_id,
        authorization_type
    )
    WHERE status = 'ACTIVE';


CREATE INDEX idx_board_member_legal_entity
    ON legal_entity_board_member(legal_entity_customer_id);

CREATE INDEX idx_board_member_customer
    ON legal_entity_board_member(customer_id);

CREATE INDEX idx_board_member_status
    ON legal_entity_board_member(status);


CREATE INDEX idx_shareholder_legal_entity
    ON legal_entity_shareholder(legal_entity_customer_id);

CREATE INDEX idx_shareholder_customer
    ON legal_entity_shareholder(shareholder_customer_id);

CREATE INDEX idx_shareholder_status
    ON legal_entity_shareholder(status);


CREATE INDEX idx_account_mandate_account_id
    ON account_mandate(account_id);

CREATE INDEX idx_account_mandate_status
    ON account_mandate(status);


CREATE INDEX idx_account_mandate_party_customer_id
    ON account_mandate_party(customer_id);

CREATE UNIQUE INDEX uq_account_mandate_party_active
    ON account_mandate_party(mandate_id, customer_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_account_mandate_party_status
    ON account_mandate_party(status);


CREATE UNIQUE INDEX uq_account_mandate_rule_active
    ON account_mandate_rule(mandate_id, operation_type)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_account_mandate_rule_status
    ON account_mandate_rule(status);
