-- ============================================================
-- Core Banking Database
-- Schema 008
-- Transaction and Transaction Entry
-- PostgreSQL
-- ============================================================

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transaction_number VARCHAR(50) NOT NULL,

    transaction_type VARCHAR(20) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'INITIATED',

    channel VARCHAR(20) NOT NULL,

    amount NUMERIC NOT NULL,

    currency_id BIGINT NOT NULL,

    reverses_transaction_id BIGINT,

    initiated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    completed_at TIMESTAMP,

    description VARCHAR(500),

    reference_number VARCHAR(100),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_transaction_number
        UNIQUE (transaction_number),

    CONSTRAINT fk_transaction_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT fk_transaction_reverses
        FOREIGN KEY (reverses_transaction_id)
        REFERENCES transaction(id),

    CONSTRAINT ck_transaction_number
        CHECK (transaction_number <> ''),

    CONSTRAINT ck_transaction_type
        CHECK (
            transaction_type IN (
                'DEPOSIT',
                'WITHDRAWAL',
                'TRANSFER',
                'PAYMENT',
                'FEE',
                'REVERSAL'
            )
        ),

    CONSTRAINT ck_transaction_status
        CHECK (
            status IN (
                'INITIATED',
                'PROCESSING',
                'COMPLETED',
                'FAILED',
                'CANCELLED',
                'REVERSED'
            )
        ),

    CONSTRAINT ck_transaction_channel
        CHECK (
            channel IN (
                'BRANCH',
                'ATM',
                'MOBILE',
                'INTERNET',
                'API',
                'SYSTEM'
            )
        ),

    CONSTRAINT ck_transaction_amount
        CHECK (amount > 0),

    CONSTRAINT ck_transaction_completed_at
        CHECK (
            completed_at IS NULL
            OR completed_at >= initiated_at
        ),

    CONSTRAINT ck_transaction_reversal_reference
        CHECK (
            transaction_type <> 'REVERSAL'
            OR reverses_transaction_id IS NOT NULL
        ),

    CONSTRAINT ck_transaction_not_self_reversal
        CHECK (
            reverses_transaction_id IS NULL
            OR reverses_transaction_id <> id
        )
);


CREATE TABLE transaction_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transaction_id BIGINT NOT NULL,

    account_id BIGINT NOT NULL,

    entry_type VARCHAR(20) NOT NULL,

    amount NUMERIC NOT NULL,

    currency_id BIGINT NOT NULL,

    sequence_no INTEGER NOT NULL,

    description VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transaction_entry_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transaction(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_transaction_entry_account
        FOREIGN KEY (account_id)
        REFERENCES account(id),

    CONSTRAINT fk_transaction_entry_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT uq_transaction_entry_sequence
        UNIQUE (transaction_id, sequence_no),

    CONSTRAINT ck_transaction_entry_type
        CHECK (
            entry_type IN (
                'SOURCE',
                'DESTINATION'
            )
        ),

    CONSTRAINT ck_transaction_entry_amount
        CHECK (amount > 0),

    CONSTRAINT ck_transaction_entry_sequence
        CHECK (sequence_no > 0)
);


CREATE INDEX idx_transaction_currency_id
    ON transaction(currency_id);

CREATE INDEX idx_transaction_status
    ON transaction(status);

CREATE INDEX idx_transaction_type
    ON transaction(transaction_type);

CREATE INDEX idx_transaction_channel
    ON transaction(channel);

CREATE INDEX idx_transaction_initiated_at
    ON transaction(initiated_at);

CREATE INDEX idx_transaction_reference_number
    ON transaction(reference_number);

CREATE INDEX idx_transaction_reverses_transaction_id
    ON transaction(reverses_transaction_id);


CREATE INDEX idx_transaction_entry_account_id
    ON transaction_entry(account_id);

CREATE INDEX idx_transaction_entry_currency_id
    ON transaction_entry(currency_id);

CREATE INDEX idx_transaction_entry_transaction_id
    ON transaction_entry(transaction_id);
