-- ============================================================
-- Core Banking Database
-- Schema 009
-- Journal, Journal Entry and Transaction Fee
-- PostgreSQL
-- ============================================================

CREATE TABLE journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transaction_id BIGINT NOT NULL,

    posting_date DATE NOT NULL DEFAULT CURRENT_DATE,

    value_date DATE NOT NULL DEFAULT CURRENT_DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    description VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_journal_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transaction(id),

    CONSTRAINT ck_journal_status
        CHECK (
            status IN (
                'DRAFT',
                'POSTED',
                'REVERSED'
            )
        ),

    CONSTRAINT ck_journal_value_date
        CHECK (value_date >= posting_date)
);


CREATE TABLE journal_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    journal_id BIGINT NOT NULL,

    sequence_no INTEGER NOT NULL,

    ledger_account_id BIGINT NOT NULL,

    account_id BIGINT,

    currency_id BIGINT NOT NULL,

    debit_amount NUMERIC NOT NULL DEFAULT 0,

    credit_amount NUMERIC NOT NULL DEFAULT 0,

    description VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_journal_entry_journal
        FOREIGN KEY (journal_id)
        REFERENCES journal(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_journal_entry_ledger_account
        FOREIGN KEY (ledger_account_id)
        REFERENCES ledger_account(id),

    CONSTRAINT fk_journal_entry_account
        FOREIGN KEY (account_id)
        REFERENCES account(id),

    CONSTRAINT fk_journal_entry_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT uq_journal_entry_sequence
        UNIQUE (journal_id, sequence_no),

    CONSTRAINT ck_journal_entry_sequence
        CHECK (sequence_no > 0),

    CONSTRAINT ck_journal_entry_debit
        CHECK (debit_amount >= 0),

    CONSTRAINT ck_journal_entry_credit
        CHECK (credit_amount >= 0),

    CONSTRAINT ck_journal_entry_debit_or_credit
        CHECK (
            (debit_amount > 0 AND credit_amount = 0)
            OR
            (debit_amount = 0 AND credit_amount > 0)
        )
);


CREATE TABLE transaction_fee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transaction_id BIGINT NOT NULL,

    fee_type VARCHAR(50) NOT NULL,

    amount NUMERIC NOT NULL,

    currency_id BIGINT NOT NULL,

    ledger_account_id BIGINT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transaction_fee_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transaction(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_transaction_fee_currency
        FOREIGN KEY (currency_id)
        REFERENCES currency(id),

    CONSTRAINT fk_transaction_fee_ledger_account
        FOREIGN KEY (ledger_account_id)
        REFERENCES ledger_account(id),

    CONSTRAINT ck_transaction_fee_type
        CHECK (fee_type <> ''),

    CONSTRAINT ck_transaction_fee_amount
        CHECK (amount > 0)
);


CREATE INDEX idx_journal_transaction_id
    ON journal(transaction_id);

CREATE INDEX idx_journal_posting_date
    ON journal(posting_date);

CREATE INDEX idx_journal_value_date
    ON journal(value_date);

CREATE INDEX idx_journal_status
    ON journal(status);


CREATE INDEX idx_journal_entry_ledger_account_id
    ON journal_entry(ledger_account_id);

CREATE INDEX idx_journal_entry_account_id
    ON journal_entry(account_id);

CREATE INDEX idx_journal_entry_currency_id
    ON journal_entry(currency_id);

CREATE INDEX idx_journal_entry_journal_id
    ON journal_entry(journal_id);


CREATE INDEX idx_transaction_fee_transaction_id
    ON transaction_fee(transaction_id);

CREATE INDEX idx_transaction_fee_currency_id
    ON transaction_fee(currency_id);

CREATE INDEX idx_transaction_fee_ledger_account_id
    ON transaction_fee(ledger_account_id);
